[project]
name = "taskr"
version = "0.1.0"
dependencies = [
    "click==8.1.7",
    "flask==3.0.2",
    "gunicorn==22.0.0",
    "requests==2.31.0",
    "tabulate==0.9.0",
]

[project.scripts]
taskr = "taskr.cli:main"
taskrd = "taskrd.cli:main"
